name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4   # latest version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile --windowed main.py   # change to flightreservation.py if that's your file

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: FlightReservationEXE
          path: dist/main.exe
